WebApplication1/Controllers/accountController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using WebApplication1.v_model;
using WebApplication1.validation;

namespace WebApplication1.Controllers
{
    
    public class accountController : Controller
    {
        private readonly appcomtext appcomtext;
        private readonly UserManager<appuser> userManager;
        private readonly SignInManager<appuser> signInManager;

        public accountController(appcomtext appcomtext,UserManager<appuser> userManager,SignInManager<appuser> signInManager)
        {
            this.appcomtext = appcomtext;
            this.userManager = userManager;
            this.signInManager = signInManager;
        }
         public IActionResult add()
        {
            return View();
        }
        [HttpPost]
        public async Task <IActionResult> reg(regvm regvm)
        {
            appuser appuser= new appuser();
            if(ModelState.IsValid )
            {
                appuser.UserName=regvm.name;
                appuser.address=regvm.address;
                appuser.PasswordHash = regvm.password;
                appuser.PhoneNumber = regvm.phone;
               IdentityResult result=await  userManager.CreateAsync(appuser,regvm.password);
                if (result.Succeeded)
                {
                    
                  await  userManager.AddToRoleAsync(appuser, "admin");
                   await signInManager.SignInAsync(appuser,false);
                    return RedirectToAction("index", "data");
                }
                foreach(var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
            }
            return View("add",regvm);
        }

        //
        public IActionResult log()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> slog(logvm logvm)
        {
            if (ModelState.IsValid)
            {
                appuser appuser = await userManager.FindByNameAsync(logvm.UserName);
                if (appuser != null)
                {
                    bool found = await userManager.CheckPasswordAsync(appuser, logvm.Password);
                    if (found == true)
                    {
                       
                        await signInManager.SignInAsync(appuser, logvm.Remmber);
                        return RedirectToAction("index", "data");
                    }
                }
                ModelState.AddModelError("", "name or password in valid");
            }
            return View("log", logvm);
        }


        public async Task<IActionResult> sout()
        {
            await signInManager.SignOutAsync();
            return View("log");
        }


    }
}

WebApplication1/Controllers/roleController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.v_model;
using WebApplication1.validation;

namespace WebApplication1.Controllers
{
    [ex]
    public class roleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;

        public roleController(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }

       
        public IActionResult add()
        {
            return View("add");
        }
        public async Task<IActionResult> saverole(rolevm rolevm)
        {
            if (ModelState.IsValid)
            {
                IdentityRole role = new IdentityRole();
                role.Name = rolevm.name;
                IdentityResult result = await roleManager.CreateAsync(role);
                if (result.Succeeded)
                {
                    ViewBag.sucess = true;
                    return Content("role is added");
                }
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }

            }
            return View("add", rolevm);
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> Back </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                        @if (User.Identity.IsAuthenticated == true)
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="account" asp-action="sout">LogOut</a>
                            </li>

                            @if (User.IsInRole("admin"))
                            {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="account" asp-action="add">Regester</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="role" asp-action="add" >Add Role</a>
                            </li>
                            }

                        }
                         
                         
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="account" asp-action="log">LogIn</a>
                        </li>
                                            
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="text-center">
             <h1 class="display-4 fw-bolder">this application for courses centre</h1></div>
           @*  &copy; 2024 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>