WebApplication1/Controllers/catController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using WebApplication1.repo;
using WebApplication1.validation;

namespace WebApplication1.Controllers
{
    [Authorize]
    
    public class catController : Controller
    {
        private readonly Icategory icategory;

        public catController(Icategory icategory)
        {
            this.icategory = icategory;
        }

        public IActionResult index()
        {
            List<category> categories  = icategory.all();

            return View(categories);
        }
        //

        public IActionResult add()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult sadd(category category)
        {
            if (ModelState.IsValid)
            {

                icategory.add(category);
                icategory.save();
                return RedirectToAction("index");
            }
            return View("add", category);
        }
        //

        public IActionResult edite(int id)
        {
            category category = icategory.Get(id);
            return View(category);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult sedite(int id, category model)
        {
           category category = icategory.Get(id);

            if (ModelState.IsValid)
            {
               category.Name = model.Name;
                icategory.update(category);
                icategory.save();
                return RedirectToAction("index");
            }
            return View("edite", model);
        }

        //
        public IActionResult delete(int id)
        {
            category category = icategory.Get(id);
            if (category == null)
            {
                return Content("No course by this id");
            }
            icategory.delete(id);
            icategory.save();
            return RedirectToAction("index");
        }
    }
}

WebApplication1/Views/cat/add.cshtml
@model WebApplication1.Models.category

@{
    ViewData["Title"] = "add";
}

<div class="row">
    <div class="col-md-4 mx-auto rounded border p-3">

        <h1 class="text-center mb-5 text-primary">Add Categories</h1>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="sadd" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group row">
                <div class=" col-sm-4 d-grid">

                    <input type="submit" value="Add" class="btn btn-danger" />
                </div>
            </div>
        </form>
    </div>
</div>

<br />
<div class="row">
    <div class=" col-sm-4 d-grid">
        <a class="btn btn-outline-primary" asp-action="index" role="button">Back to List</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/Views/cat/edite.cshtml
@model WebApplication1.Models.category

@{
    ViewData["Title"] = "edite";
}

<div class="row">
    <div class="col-md-4 mx-auto rounded border p-3">
        <h1 class="text-center mb-5 text-primary">Edite Category</h1>
    </div>
</div>

<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="sedite" asp-route-id="@Model.Id" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group row">
                <div class=" col-sm-4 d-grid">

                    <input type="submit" value="Edite" class="btn btn-danger" />
                </div>
            </div>
        </form>
    </div>
</div>
<br />
<div class="row">
    <div class=" col-sm-4 d-grid">
        <a class="btn btn-outline-primary" asp-action="index" role="button">Back to List</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/Views/cat/index.cshtml
@model List<category>
@{
    ViewData["Title"] = "index";
}

<div class="row">
    <div class="col-md-4 mx-auto rounded border p-3">

        <h1 class="text-center mb-5 text-primary "> All Categories</h1>
    </div>
</div>

<div class="row">
    <div class="col">
        <a class="btn btn-primary" asp-controller="cat" asp-action="add"> Add Category</a>
    </div>
</div>

<br />
<table class="table">
    <thead>
        <tr>
            <th> ID</th>
            <th> Name</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td> @item.Id</td>
                <td> @item.Name</td>
                <td style="white-space:nowrap">
                    <a class="btn btn-primary btn-sm" asp-controller="cat" asp-action="edite" asp-route-id="@item.Id">EDITE</a>
                    <a class="btn btn-danger btn-sm" asp-controller="cat" asp-action="delete"
                       asp-route-id="@item.Id" onclick="return confirm ('are you sure?')">    Delete</a>
                </td>
            </tr>
        }
    </tbody>

</table>