WebApplication1/Models/trainer.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public class trainer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public int age { get; set; }

        [ForeignKey("courses")]
        public int courseid {  get; set; }
        public Courses? courses { get; set; }
    }
}

WebApplication1/Controllers/trainerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Blazor;
using WebApplication1.Models;
using WebApplication1.repo;
using WebApplication1.validation;

namespace WebApplication1.Controllers
{
    [Authorize]
    [ex]
    public class trainerController : Controller
    {
        private readonly Itrainer itrainer;
        private readonly Icourserepo icourserepo;

        public trainerController(Itrainer itrainer,Icourserepo icourserepo)
        {
            this.itrainer = itrainer;
            this.icourserepo = icourserepo;
        }

        public IActionResult index()
        {
            List<trainer> trainers = itrainer.all();
            return View(trainers);
        }
        //
        public IActionResult add()
        {
            ViewData["cslist"] = icourserepo.all();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult sadd( trainer trainer)
        {
            if (ModelState.IsValid)
            {
                itrainer.add(trainer);
                itrainer.save();
                return RedirectToAction("index");
            }
            return View("add",trainer);
        }
        //
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult edite(int id)
        {
            trainer trainer= itrainer.Get(id);
            ViewData["cslist"] = icourserepo.all();
            return View(trainer);
        }
        [HttpPost]
         public IActionResult sedite(int id,trainer model)
        {
            trainer trainer =itrainer.Get(id);
            if (ModelState.IsValid)
            {
                trainer.Name=model.Name;
                trainer.phone= model.phone;
                trainer.address= model.address;
                trainer.courseid= model.courseid;
                trainer.age= model.age;
                 
                itrainer.save();
                return RedirectToAction("index");
            }
            ViewData["cslist"] = icourserepo.all();
            return View("edite", model);
        }
        //

        public IActionResult delete(int id)
        {
            trainer trainer = itrainer.Get(id);
            if (trainer == null)
            {
                return Content("No course by this id");
            }
            itrainer.delete(id);
           itrainer.save();
            return RedirectToAction("index");
        }

    }
}

WebApplication1/Views/trainer/add.cshtml
@model WebApplication1.Models.trainer

@{
    ViewData["Title"] = "add";
    SelectList selcat = new SelectList(ViewBag.cslist, "Id", "Name");

}

<div class="row">
    <div class="col-md-4 mx-auto rounded border p-3">

        <h1 class="text-center  mb-5 text-primary "> Add Trainer</h1>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="sadd">
            <div asp-validation-summary="All" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="phone" class="control-label"></label>
                <input asp-for="phone" class="form-control" />
                <span asp-validation-for="phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address" class="control-label"></label>
                <input asp-for="address" class="form-control" />
                <span asp-validation-for="address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="age" class="control-label"></label>
                <input asp-for="age" class="form-control" />
                <span asp-validation-for="age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="courseid" class="control-label"></label>
                <select asp-for="courseid" class="form-control" asp-items="selcat" >
                    <option value="0">--slecte--</option>
                </select>
                <span asp-validation-for="courseid" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group row">
                <div class=" col-sm-4 d-grid">

                    <input type="submit" value="Save" class="btn btn-danger" />
                </div>
            </div>
        </form>
    </div>
</div>

<br />
<div class="row">
    <div class=" col-sm-4 d-grid">
        <a class="btn btn-outline-primary" asp-action="index" role="button">Back to List</a>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/Views/trainer/edite.cshtml
@model WebApplication1.Models.trainer

@{
    ViewData["Title"] = "edite";
    SelectList selcat = new SelectList(ViewBag.cslist, "Id", "Name");

}

<div class="row">
    <div class="col-md-4 mx-auto rounded border p-3">

        <h1 class="text-center  mb-5 text-primary "> Edite Trainer</h1>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="sedite" asp-route-id="@Model.Id" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="phone" class="control-label"></label>
                <input asp-for="phone" class="form-control" />
                <span asp-validation-for="phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address" class="control-label"></label>
                <input asp-for="address" class="form-control" />
                <span asp-validation-for="address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="age" class="control-label"></label>
                <input asp-for="age" class="form-control" />
                <span asp-validation-for="age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="courseid" class="control-label"></label>
                <select asp-for="courseid" class="form-control" asp-items="selcat"></select>
                <span asp-validation-for="courseid" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group row">
                <div class=" col-sm-4 d-grid">

                    <input type="submit" value="Edite" class="btn btn-danger" />
                </div>
            </div>
        </form>
    </div>
</div>

<br />
<div class="row">
    <div class=" col-sm-4 d-grid">
        <a class="btn btn-outline-primary" asp-action="index" role="button">Back to List</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/Views/trainer/index.cshtml
@model List<trainer>
@{
    ViewData["Title"] = "index";
}

<div class="row">
    <div class="col-md-4 mx-auto rounded border p-3">

        <h1 class="text-center mb-5 text-primary "> All Trainers</h1>
    </div>
</div>

<div class="row">
    <div class="col">
        <a class="btn btn-primary" asp-controller="trainer" asp-action="add"> Add Trainer</a>
    </div>
</div>

<br />
<table class="table">
    <thead>
        <tr>
            <th> ID</th>
            <th> Name</th>
            <th> Phone</th>
            <th> Address</th>
            <th> Age</th>
            <th>course</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td> @item.Id</td>
                <td> @item.Name</td>
                <td>@item.phone</td>
                <td>@item.address</td>
                <td>@item.age</td>
                <td>@item.courses.Name</td>
                                
                <td style="white-space:nowrap">
                    <a class="btn btn-primary btn-sm" asp-controller="trainer" asp-action="edite" asp-route-id="@item.Id">EDITE</a>
                    <a class="btn btn-danger btn-sm" asp-controller="trainer" asp-action="delete"
                       asp-route-id="@item.Id" onclick="return confirm ('are you sure?')">    Delete</a>
                </td>
            </tr>
        }
    </tbody>

</table>