WebApplication1/Models/labs.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using WebApplication1.validation;

namespace WebApplication1.Models
{
    public class labs
    {
        public int Id { get; set; }
        [Required]
        [uniqname]
        public string name { get; set; }
        public ICollection<Courses>? courses { get; set; }

    }
}

WebApplication1/Controllers/labController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Abstractions;
using Microsoft.Identity.Client;
using WebApplication1.Models;
using WebApplication1.repo;
using WebApplication1.validation;

namespace WebApplication1.Controllers
{
    [Authorize]
    [ex]
    public class labController : Controller
    {
        private readonly Ilabs ilabs;

        public labController(Ilabs ilabs)
        {
            this.ilabs = ilabs;
        }

        public IActionResult inndex()
        {
            List<labs> labs = ilabs.all();
            
            return View(labs );
        }
        //

        public IActionResult add()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult sadd(labs labs)
        {
            if(ModelState.IsValid)
            {

                ilabs.add(labs);
                ilabs.save();
                return RedirectToAction("inndex");
            }
            return View("add",labs);
        }
        //

        public IActionResult edite(int id)
        {
           labs labs= ilabs.Get(id);
            return View(labs);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult sedite(int id,labs model)
        {
            labs labs= ilabs.Get(id);

            if (ModelState.IsValid)
            {
                labs.name = model.name;
                ilabs.update(labs);
                ilabs.save();
                return RedirectToAction("inndex");
            }
            return View("edite", model);
        }

        //
        public IActionResult delete(int id)
        {
            labs labs = ilabs.Get(id);
            if (labs == null)
            {
                return Content("No course by this id");
            }
             ilabs.delete(id);
            ilabs.save();
            return RedirectToAction("inndex");
        }

    }
}

WebApplication1/Views/lab/add.cshtml
@model WebApplication1.Models.labs

@{
    ViewData["Title"] = "add";
}

<div class="row">
    <div class="col-md-4 mx-auto rounded border p-3">

        <h1 class="text-center mb-5 text-primary">Add Labs</h1>
    </div>
</div>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="sadd"  method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group row">
                <div class=" col-sm-4 d-grid">

                    <input type="submit" value="Add" class="btn btn-danger" />
                </div>
            </div>
        </form>
    </div>
</div>
<br />
<div class="row">
    <div class=" col-sm-4 d-grid">
        <a class="btn btn-outline-primary" asp-action="inndex" role="button">Back to List</a>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/Views/lab/edite.cshtml
@model WebApplication1.Models.labs

@{
    ViewData["Title"] = "edite";
}
<div class="row">
    <div class="col-md-4 mx-auto rounded border p-3">

        <h1 class="text-center mb-5 text-primary">Edite Labs</h1>
    </div>
</div>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="sedite" asp-route-id="@Model.Id" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group row">
                <div class=" col-sm-4 d-grid">

                    <input type="submit" value="Edite" class="btn btn-danger" />
                </div>
            </div>
        </form>
    </div>
</div>

<br />

<div class="row">
    <div class=" col-sm-4 d-grid">
        <a class="btn btn-outline-primary" asp-action="inndex" role="button">Back to List</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/Views/lab/inndex.cshtml
@model List<labs>
@{
    ViewData["Title"] = "inndex";
}

<div class="row">
    <div class="col-md-4 mx-auto rounded border p-3">

        <h1 class="text-center mb-5 text-primary "> All Labs</h1>
    </div>
</div>

<div class="row">
    <div class="col">
        <a class="btn btn-primary" asp-controller="lab" asp-action="add"> Add Lab</a>
    </div>
</div>

<br />
<table class="table">
    <thead>
        <tr>
            <th> ID</th>
            <th> Name</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td> @item.Id</td>
                <td> @item.name</td>
                <td style="white-space:nowrap">
                    <a class="btn btn-primary btn-sm" asp-controller="lab" asp-action="edite" asp-route-id="@item.Id">EDITE</a>
                    <a class="btn btn-danger btn-sm" asp-controller="lab" asp-action="delete"
                       asp-route-id="@item.Id" onclick="return confirm ('are you sure?')">    Delete</a>
                </td>
            </tr>
        }
    </tbody>

</table>